=== Pacifico53/PRI2020/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT projectRecord (title, data, team, abstract, deliverables) >

<!ELEMENT title (#PCDATA) >

<!ELEMENT data (key_name, title, subtitle*, begin_date, end_date, supervisor) >
<!ELEMENT key_name (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
            href CDATA #REQUIRED>

<!ELEMENT team (element+) >
<!ELEMENT element (name, email) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (paragraph+) >
<!ELEMENT paragraph (line+) >
<!ELEMENT line (#PCDATA|bold|italic|ref)* >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >

<!ELEMENT deliverables (ref+) >
<!ELEMENT ref (#PCDATA) >
<!ATTLIST ref
            href CDATA #REQUIRED>

=== Pacifico53/PRI2020/TP5/PR/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "PR.dtd">
<projectRecord>
    <title>Project Record</title>
    <data>
        <key_name>TP5</key_name>
        <title>Servidor NodeJS</title>
        <subtitle>Trabalho de casa 5</subtitle>
        <begin_date>09/11/2020</begin_date>
        <end_date>16/11/10</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </data>
    <team>
        <element>
            <name>Bernardo Viseu</name>
            <email>a74618@alunos.uminho.pt</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Neste projecto foi definido um servidor NodeJS que reponda a pedidos sobre um dataset de uma escola de musica.</line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="https://github.com/Pacifico53/PRI2020">Repositório de PRI</ref>
    </deliverables>
</projectRecord>

=== Pacifico53/PRI2020/TPC/TP4/PR/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "PR.dtd">
<projectRecord>
    <title>Project Record</title>
    <data>
        <key_name>TP2</key_name>
        <title>Servidor NodeJS e Indice XSL</title>
        <subtitle>Trabalho de casa 4</subtitle>
        <begin_date>02/11/2020</begin_date>
        <end_date>09/11/10</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </data>
    <team>
        <element>
            <name>Bernardo Viseu</name>
            <email>a74618@alunos.uminho.pt</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Neste projecto foi definido um XSL de maneira a organizar os Arqueossitions do NW portugues, e utilizar um servidor realizado em JS para colocar o resultado HTML num localhost.</line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="https://github.com/Pacifico53/PRI2020">Repositório de PRI</ref>
    </deliverables>
</projectRecord>

=== Pacifico53/PRI2020/TPC/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "PR.dtd">
<projectRecord>
    <title>Project Record</title>
    <data>
        <key_name>TP2</key_name>
        <title>DTD, XML e XPath</title>
        <subtitle>Trabalho de casa sobre a aplicação de DTD, XML e XPath</subtitle>
        <begin_date>19/10/2020</begin_date>
        <end_date>26/10/10</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </data>
    <team>
        <element>
            <name>Bernardo Viseu</name>
            <email>a74618@alunos.uminho.pt</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Neste projecto foi realizado um ficheiro <bold>DTD</bold> a definir a estrutura de um PR, foi também feito este <bold>XML</bold> exemplo.</line>
            <line>Foi também feito algumas queries em <italic>XPath</italic>. <ref href="https://en.wikipedia.org/wiki/XPath"></ref></line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="https://github.com/Pacifico53/PRI2020">Repositório de PRI</ref>
    </deliverables>
</projectRecord>
